#!/usr/bin/env python3
"""
owl compile — Compile an openwl/ directory into a JSON agent spec for Firestore.

Usage:
    cd Xie_ECR_2026
    python3 openwl/compile.py                       # auto-detects git SHA
    python3 openwl/compile.py --output /tmp/spec.json
    python3 openwl/compile.py --dry-run              # print to stdout

The compiler:
  1. Reads agent.yaml for metadata + intelligence + tool definitions
  2. For each tool, reads tool.yaml (parameters, outputs) + script.R (code)
  3. Injects shared/ R helpers into each script via bash wrapper
  4. Uses git commit SHA as version (immutable, traceable)
  5. Adds sourceUrl linking back to the exact commit on GitHub

Output JSON is compatible with `ptbl-admin agent update <id> <file.json>`.
"""

import json
import os
import re
import subprocess
import sys
import argparse
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)


def get_git_info(repo_dir: str) -> dict:
    """Get git commit SHA, short SHA, and remote URL."""
    def run(cmd):
        try:
            return subprocess.check_output(cmd, cwd=repo_dir, stderr=subprocess.DEVNULL).decode().strip()
        except (subprocess.CalledProcessError, FileNotFoundError):
            return None

    sha = run(["git", "rev-parse", "HEAD"])
    short_sha = run(["git", "rev-parse", "--short", "HEAD"])
    remote = run(["git", "remote", "get-url", "origin"])

    # Normalize remote URL to HTTPS browse URL
    repo_url = None
    if remote:
        remote = remote.replace(".git", "")
        if remote.startswith("git@"):
            remote = remote.replace("git@github.com:", "https://github.com/")
        repo_url = remote

    return {
        "sha": sha or "unknown",
        "shortSha": short_sha or "unknown",
        "repoUrl": repo_url or "https://github.com/openwl-org/Xie_ECR_2026",
    }


def camel_to_upper_snake(name: str) -> str:
    """Convert camelCase to UPPER_SNAKE_CASE for env var names.
    Must match ptbl-task-mcp's conversion exactly:
      deltaCTFile → DELTA_CT_FILE (not DELTA_CTFILE)
    """
    # Step 1: Split consecutive uppercase before a lowercase: CTFile → CT_File
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
    # Step 2: Split lowercase/digit before uppercase: delta_CT → delta_CT (already done), deltaC → delta_C
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s)
    return s.upper()


def build_bash_wrapper(tool_name: str, script_r: str, shared_files: dict, params: dict) -> str:
    """
    Build a bash wrapper that:
    1. Writes shared R helpers to a temp dir
    2. Sets SHARED_DIR env var
    3. Writes the tool's script.R
    4. Runs it via Rscript
    """
    lines = []

    # Header
    lines.append(f"# Auto-generated by owl compile — do not edit")
    lines.append(f"# Tool: {tool_name}")
    lines.append("")

    # Set up shared dir with embedded helpers
    lines.append("# Write shared R helpers")
    lines.append("SHARED_DIR=$(mktemp -d)")
    lines.append("export SHARED_DIR")

    for filename, content in shared_files.items():
        # Use heredoc to write each shared file
        lines.append(f"cat > \"$SHARED_DIR/{filename}\" << 'SHARED_EOF'")
        lines.append(content)
        lines.append("SHARED_EOF")
        lines.append("")

    # Set up env vars from parameters
    lines.append("# Export tool parameters as env vars")
    for param_name in params:
        env_name = camel_to_upper_snake(param_name)
        lines.append(f'export {env_name}="${{{env_name}:-}}"')
    lines.append("")

    # Write the R script
    lines.append(f"# Write tool script")
    lines.append("cat > /tmp/tool_script.R << 'TOOL_RSCRIPT_EOF'")
    lines.append(script_r)
    lines.append("TOOL_RSCRIPT_EOF")
    lines.append("")

    # Run it
    lines.append("Rscript /tmp/tool_script.R 2>&1")
    lines.append("R_EXIT=$?")
    lines.append(f'[ $R_EXIT -ne 0 ] && echo "[{tool_name}] ERROR: exit $R_EXIT" && exit $R_EXIT')
    lines.append(f'echo "[{tool_name}] Output files:" && ls -lh /output/')

    return "\n".join(lines)


def compile_agent(openwl_dir: str, git_info: dict) -> dict:
    """Compile the openwl/ directory into a Firestore-compatible JSON spec."""
    openwl = Path(openwl_dir)

    # 1. Read agent.yaml
    with open(openwl / "agent.yaml") as f:
        agent_yaml = yaml.safe_load(f)

    agent_id = agent_yaml["name"]
    sha = git_info["sha"]
    short_sha = git_info["shortSha"]
    repo_url = git_info["repoUrl"]
    source_url = f"{repo_url}/tree/{sha}/openwl"

    # 2. Read shared helpers
    shared_dir = openwl / "shared"
    shared_files = {}
    if shared_dir.exists():
        for f in sorted(shared_dir.glob("*.R")):
            shared_files[f.name] = f.read_text()

    # 3. Read existing spec to preserve iconUrl, createdAt, etc.
    # (These get merged in later — the compiler just produces the spec)

    # 4. Build tool specs
    tools = {}
    tools_dir = openwl / "tools"
    docker_config = agent_yaml.get("docker", {})
    default_image = docker_config.get("image", "")
    default_resources = docker_config.get("resources", {})

    for tool_dir in sorted(tools_dir.iterdir()):
        if not tool_dir.is_dir():
            continue

        tool_yaml_path = tool_dir / "tool.yaml"
        script_r_path = tool_dir / "script.R"

        if not tool_yaml_path.exists():
            print(f"  WARN: {tool_dir.name}/ has no tool.yaml, skipping", file=sys.stderr)
            continue

        with open(tool_yaml_path) as f:
            tool_yaml = yaml.safe_load(f)

        tool_name = tool_yaml.get("name", tool_dir.name)

        # Read script.R if present
        script_r = ""
        if script_r_path.exists():
            script_r = script_r_path.read_text()

        # Build parameters spec
        params = tool_yaml.get("parameters", {})
        param_properties = {}
        required = []
        for pname, pspec in params.items():
            prop = {"type": pspec.get("type", "string")}
            if "format" in pspec:
                prop["format"] = pspec["format"]
            if "description" in pspec:
                prop["description"] = pspec["description"]
            if "default" in pspec:
                prop["default"] = pspec["default"]
            param_properties[pname] = prop
            # file params are typically required
            if pspec.get("format") == "file" and not pspec.get("optional", False):
                required.append(pname)

        # Build outputs spec
        output_files = tool_yaml.get("outputFiles", [])
        outputs = {}
        if output_files:
            outputs[f"{tool_name}_output"] = {
                "semantic": "analysis_results",
                "description": tool_yaml.get("description", ""),
                "file_patterns": output_files,
            }

        # Build env var list from parameters
        env_vars = [camel_to_upper_snake(p) for p in params]
        env_vars.extend(["INPUT_FILES", "TASK_DIR"])

        # Build bash wrapper with embedded shared code + R script
        bash_code = build_bash_wrapper(tool_name, script_r, shared_files, params)

        tools[tool_name] = {
            "type": "docker",
            "description": tool_yaml.get("description", ""),
            "version": short_sha,
            "image": default_image,
            "parameters": {
                "type": "object",
                "required": required,
                "properties": param_properties,
            },
            "outputs": outputs,
            "resources": {
                "cpuMilli": default_resources.get("cpuMilli", 2000),
                "memoryMib": default_resources.get("memoryMib", 8192),
                "timeout": "30m",
                "ephemeralStorageGib": 10,
            },
            "scriptSpec": {
                "env": env_vars,
                "requiredInputs": [camel_to_upper_snake(p) for p in required],
                "steps": [
                    {
                        "language": "bash",
                        "name": tool_name,
                        "code": bash_code,
                    }
                ],
            },
        }

    # 5. Inject platform tools (required by Temporal delegation workflow)
    # These are NOT R analysis tools — they're system/MCP tools that every
    # specialist needs for the ReWOO planning pattern and file discovery.
    tools["search_vault"] = {
        "name": "search_vault",
        "type": "mcp",
        "description": "Search vault storage for files by pattern, extension, or size. Searches notebook files, task outputs, platform files, and external public buckets.",
        "implementation": {
            "server": "ptbl-files",
            "method": "search_vault"
        },
        "inputSchema": {
            "type": "object",
            "properties": {
                "notebookId": {
                    "type": "string",
                    "description": "Notebook ID to search in"
                },
                "pattern": {
                    "type": "string",
                    "description": "Regex pattern to match filenames (e.g. '.*\\.csv' for CSV files)"
                },
                "extension": {
                    "type": "string",
                    "description": "File extension filter (e.g. '.csv', '.xlsx')"
                }
            },
            "required": ["notebookId"]
        }
    }

    tools["postMessage"] = {
        "name": "postMessage",
        "type": "mcp",
        "description": "Post message to user",
        "implementation": {
            "server": "ptbl-messages",
            "method": "add_agent_message"
        },
        "inputSchema": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "messageType": {
                    "type": "string",
                    "enum": ["update", "result", "question", "reasoning"]
                }
            },
            "required": ["message", "messageType"]
        }
    }

    tools["submit_execution_plan"] = {
        "type": "system",
        "description": "Submit a batch execution plan using parallel arrays. Each task is defined by its index across the arrays.",
        "parameters": {
            "type": "object",
            "required": ["taskToolNames", "description"],
            "properties": {
                "taskToolNames": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Tool name for each task"
                },
                "taskInputFiles": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Comma-separated /pfs/ file paths per task. Empty string if no files needed."
                },
                "taskDependsOn": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Comma-separated 0-based indices of dependency tasks. Empty string = no dependencies."
                },
                "taskToolParameters": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "JSON string of non-file parameters per task. Empty string if no extra params."
                },
                "taskScatter": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Scatter mode per task. Empty string = single task (default)."
                },
                "description": {
                    "type": "string",
                    "description": "Human-readable plan description"
                }
            }
        }
    }

    # 6. Build intelligence section
    #    (was step 5 before platform tool injection)
    intel_yaml = agent_yaml.get("intelligence", {})
    instruction_sections = {}
    for section_name, section_data in intel_yaml.get("instructionSections", {}).items():
        instruction_sections[section_name] = {
            "order": section_data.get("order", 1),
            "enabled": section_data.get("enabled", True),
            "content": section_data.get("content", ""),
        }

    intelligence = {
        "systemInstruction": intel_yaml.get("systemInstruction", ""),
        "instructionSections": instruction_sections,
    }

    # 6. Assemble the full spec
    # Display name from agent.yaml or derive from id
    display_name = agent_yaml.get("displayName", "mtDNA Transcriptomics Specialist")

    # Read iconUrl from agent.yaml if present
    icon_url = agent_yaml.get("iconUrl")

    spec = {
        "id": agent_id,
        "name": display_name,
        "version": short_sha,
        "type": "owl",
        "tier": "free",
        "status": "active",
        "specialization": agent_yaml.get("description", ""),
        "category": "domain",
        "infrastructure": {
            "language": "bash",
            "platform": "kubernetes",
            "executionMethod": "kubernetes-job",
            "executor": "rta-workspace",
            "memory": "16Gi",
            "timeout": "180m",
            "region": "us-central1",
            "runtime": {
                "llm": {
                    "provider": "google",
                    "model": "gemini-2.5-flash",
                    "config": {"temperature": 0.1, "maxOutputTokens": 8192},
                }
            },
        },
        "meta": {
            "owl": {"version": "3.0", "kind": "agent"},
            "id": agent_id,
            "name": display_name,
            "shortName": "mtDNA Txn",
            "version": short_sha,
            "tier": "free",
            "type": "owl",
            "status": "active",
            "specialization": agent_yaml.get("description", ""),
            "author": "Arking Lab / OpenWL",
            "source": {
                "repository": repo_url,
                "commit": sha,
                "directory": "openwl/",
                "url": source_url,
            },
            "changelog": [
                {
                    "version": short_sha,
                    "date": subprocess.check_output(
                        ["git", "log", "-1", "--format=%ci", sha],
                        cwd=openwl_dir,
                    )
                    .decode()
                    .strip()[:10],
                    "changes": [
                        f"Compiled from {source_url}",
                        subprocess.check_output(
                            ["git", "log", "-1", "--format=%s", sha],
                            cwd=openwl_dir,
                        )
                        .decode()
                        .strip(),
                    ],
                }
            ],
            "tags": [
                "mtdna",
                "transcriptomics",
                "mitochondria",
                "edger",
                "mixed-models",
                "mitocarta",
                "arking-lab",
                "docker-only",
                "openwl",
            ],
            "capabilities": [
                "tmm-normalization",
                "gene-regression",
                "pattern-classification",
                "go-enrichment",
                "publication-figures",
                "html-report",
            ],
        },
        "tools": tools,
        "intelligence": intelligence,
    }

    # Add iconUrl if defined in agent.yaml
    if icon_url:
        spec["iconUrl"] = icon_url

    return spec


def main():
    parser = argparse.ArgumentParser(description="Compile openwl/ directory to JSON agent spec")
    parser.add_argument("--dir", default=None, help="Path to openwl/ directory (auto-detected)")
    parser.add_argument("--output", "-o", default=None, help="Output JSON path (default: openwl/compiled/<id>.owl.json)")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout instead of writing file")
    parser.add_argument("--merge-from", default=None, help="Existing JSON spec to merge iconUrl/createdAt from")
    args = parser.parse_args()

    # Find openwl/ directory
    if args.dir:
        openwl_dir = args.dir
    else:
        # Look relative to this script
        script_dir = Path(__file__).parent
        if (script_dir / "agent.yaml").exists():
            openwl_dir = str(script_dir)
        elif (Path.cwd() / "openwl" / "agent.yaml").exists():
            openwl_dir = str(Path.cwd() / "openwl")
        else:
            print("ERROR: Cannot find agent.yaml. Run from repo root or pass --dir.", file=sys.stderr)
            sys.exit(1)

    repo_dir = str(Path(openwl_dir).parent)
    print(f"Compiling: {openwl_dir}", file=sys.stderr)

    git_info = get_git_info(repo_dir)
    print(f"Git commit: {git_info['shortSha']} ({git_info['sha'][:12]}...)", file=sys.stderr)
    print(f"Source URL: {git_info['repoUrl']}/tree/{git_info['sha']}/openwl", file=sys.stderr)

    spec = compile_agent(openwl_dir, git_info)

    # Merge preserved fields from existing spec (iconUrl, createdAt, etc.)
    if args.merge_from and os.path.exists(args.merge_from):
        print(f"Merging from: {args.merge_from}", file=sys.stderr)
        with open(args.merge_from) as f:
            text = f.read()
            # Handle ptbl-admin output (may have extra data after JSON)
            depth = 0
            end = 0
            for i, c in enumerate(text):
                if c == '{': depth += 1
                elif c == '}': depth -= 1
                if depth == 0 and i > 0:
                    end = i + 1
                    break
            existing = json.loads(text[:end])
        existing_agent = existing.get("agent", existing)
        # Preserve iconUrl
        if "iconUrl" in existing_agent:
            spec["iconUrl"] = existing_agent["iconUrl"]
            print(f"  Preserved iconUrl", file=sys.stderr)
        # Preserve createdAt
        if "createdAt" in existing_agent:
            spec["createdAt"] = existing_agent["createdAt"]
        # Append existing changelog entries
        existing_changelog = existing_agent.get("meta", {}).get("changelog", [])
        if existing_changelog:
            spec["meta"]["changelog"].extend(existing_changelog)
            print(f"  Preserved {len(existing_changelog)} changelog entries", file=sys.stderr)

    output_json = json.dumps(spec, indent=2, ensure_ascii=False)

    if args.dry_run:
        print(output_json)
    else:
        # Determine output path
        if args.output:
            out_path = args.output
        else:
            compiled_dir = Path(openwl_dir) / "compiled"
            compiled_dir.mkdir(exist_ok=True)
            out_path = str(compiled_dir / f"{spec['id']}.owl.json")

        with open(out_path, "w") as f:
            f.write(output_json)

        print(f"Wrote: {out_path}", file=sys.stderr)
        print(f"  Version: {spec['version']} (git: {git_info['sha'][:12]})", file=sys.stderr)
        print(f"  Tools: {len(spec['tools'])}", file=sys.stderr)
        print(f"  Size: {len(output_json) // 1024} KB", file=sys.stderr)
        print(f"", file=sys.stderr)
        print(f"Deploy with:", file=sys.stderr)
        print(f"  ptbl-admin agent update {spec['id']} {out_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
